### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by sheillendra** [phpindonesia/phpindonesia.or.id-membership#1]
ada yang bisa bantu modifikasi [login page](phpindonesia.or.id-membership/frontend/views/site/login.php) ?, posisi element login buat seperti facebook, tempatkan di navbar, dan pindahkan element signup ke login page ini, seperti facebook atau twitter.

Untuk layout login saya sudah buat sendiri layoutnya, dipisahkan dari layout main.

**Comment by okaprinarjaya** [comment]
halo teman-teman, gimana status issue ini? sudah ada yg pick? atau malah sudah solved?

**Comment by sheillendra** [comment]
belum, om oka saja yang pick, ya??
