### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by luridarmawan** [phpindonesia/phpindonesia.or.id-membership#11]
temen2 ....

proses development disini tinggal asal push/pull-request saja ? ga pake planning pekerjaan via project-management ?
ada baiknya mencoba method scrum/kanban/etc, disertai task2/project managementnya,
sehingga target pekerjaan selalu terjaga dan fokus sesuai timeline.

pembagian task jg akan termonitor dengan baik.
tapii.... tentu saja akan perlu seorang/lebih project-manager untuk meluangkan waktu memonitor task

cmiw

**Comment by luridarmawan** [comment]
standarisasi penulisan jg perlu dicermati sepertinya,
sy prefer menggunakan psr-2

**Comment by aNdzHaR** [comment]
+1 @luridarmawan 
![agree](https://cloud.githubusercontent.com/assets/1691763/8518371/962ac224-23f3-11e5-8999-008fdfa9ef86.jpg)

**Comment by okaprinarjaya** [comment]
om @luridarmawan , yappzz saya setuju, hari sabtu minggu kmarin saya sudah kontak yodiz melalui support@yodiz.com , hanya saja blom dapat response T_T dari yodiz http://www.yodiz.com/free-agile-software.html

Terimakasih udah dikasi solusi alternatif untuk yodiz oleh om luri, yaitu: http://wholemeal.co.nz/projects/fulcrum.html .. tapi ini perlu diinstall. gimana om @peterjkambey ? servernya boleh diinstall tools ini gak?

**Comment by sheillendra** [comment]
@luridarmawan masih belajar om, di tunggu petunjuk dan comment commentnya.

**Comment by okaprinarjaya** [comment]
Sementara pakai apa yg sudah disediakan oleh github . Om @peterjkambey , minta tolong untuk kontak om saleh untuk minta bantuan diinstall-kan https://github.com/fulcrum-agile/fulcrum . Seperti rapat kita kmarin, SEMENTARA baru saya yg jadi tukang manage task-task , klo ada yg lain berniat serius utk kontribusi, silahkan hubungi om @peterjkambey .
