### ISSUE TITLE
usul: Url profile dibuat user friendly

### ISSUE THREAD

**Issue by hscstudio** [phpindonesia/phpindonesia.or.id-membership#27]
Alangkah kerennya jika nantinya url profile dibuat user friendly.. 

phpindonesia.com/membership/username

Usul juga membership diganti dg member aja atau anggota.. biar lebih indonesia :)

Maaf nyubi cuman bisa usul doang :)

**Comment by sheillendra** [comment]
usul nyubi ini sangat bagus, jadi langsung diterima, om @peterjkambey jika perlu minta bantuan master @hscstudio untuk setting webroot dari phpindonesia.com/member

**Comment by peterjkambey** [comment]
Terserah om Surya aja.. :-D

**Comment by sheillendra** [comment]
ok
