### ISSUE TITLE
Fitur Module Mailbox

### ISSUE THREAD

**Issue by sheillendra** [phpindonesia/phpindonesia.or.id-membership#3]
Mailbox ini fitur message antara admin dengan member ataupun member dengan member.

mungkin ada yang bersedia pick??

**Comment by hscstudio** [comment]
Pke yii2-mailbox aje..

**Comment by sheillendra** [comment]
iya om hafid yang pick ya

**Comment by hscstudio** [comment]
Ane lg mudik gan 3 minggu g bawa laptop :)
